site_name: Joe Wojak | Senior Technical Writer

theme:
  name: material

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Resume: resume.md

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # --- New extensions ---
  - pymdownx.details      # For collapsible "Service Manual" style notes
  - pymdownx.superfences  # For nesting code/lists (vital for complex procedures)
  - pymdownx.tasklist:    # For field-service engineer checklists
      custom_checkbox: true
  - pymdownx.highlight:   # For professional code rendering
      anchor_linenums: true
  - pymdownx.keys         # For rendering keyboard shortcuts (e.g., Ctrl+C)
  - pymdownx.arithmatex:  # For electromechanical formulas
      generic: true